version: "3.0"

services:
  frontend:
    # Replace with your image
    image: ghcr.io/grimmweeper/bootcamp-gds-frontend:77c12e2
    command: "npm start"
    environment:
      NODE_ENV: development
      APP_URL: http://localhost:3000
      API_URL: http://backend:3001
    ports:
      - 3000:3000

  backend:
    # Replace with your image
    image: ghcr.io/grimmweeper/bootcamp-gds-backend:77c12e2
    command: "npm start"
    environment:
      NODE_ENV: development
      APP_URL: http://localhost:3000
      API_URL: http://localhost:3001
      PORT: 3001
    ports:
      - 3001:3001
